### ISSUE TITLE
Issue using migration tool with reference to SkyUrlValidationDirective

### ISSUE THREAD

**Issue by IsaacBoy** [blackbaud/skyux-sdk-builder-plugin-migrate#20]
Running the migration tool on our SPA, I got the following error: 

`(node:21904) UnhandledPromiseRejectionWarning: Error: No package found for SkyUrlValidationDirective!`

Reporting it as per the instructions on the migration guide page.

**Comment by IsaacBoy** [comment]
FYI I was able to get past the error by manually changing the import reference to `@skyux/validation`

**Comment by Blackbaud-PaulCrowder** [comment]
@IsaacBoy This is not a class I would expect to be imported in a consumer SPA.  Can you provide a code sample showing how you're using it?
