### ISSUE TITLE
Trailing comma after using the migration tool

### ISSUE THREAD

**Issue by Blackbaud-MikitaYankouski** [blackbaud/skyux-sdk-builder-plugin-migrate#21]
The first issue I had to fix after migrating https://blackbaud.visualstudio.com/Products/_git/skyux-lib-reporting-authentication was a trailing comma at the end of exports in the app-extras.module.ts.

**Comment by Blackbaud-SteveBrush** [comment]
Confirmed that this occurs when the exports are formatted as:
```
exports: [
],
```

**Comment by Blackbaud-AlexKingman** [comment]
This only happens when certain variables are present. Plus, the usage of the migration tool should be minimal now. Closing.
