### ISSUE TITLE
@pact-foundation/pact should be included as a dev dependency

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-sdk-builder-plugin-migrate#23]
Running `skyux pact` results in
`E/launcher - Error: Error: Cannot find module '@pact-foundation/pact'`
if `@pact-foundation/pact` is an installed package.

The migration utility currently updates package.json file to include `@pact-foundation/pact-web`.  `@pact-foundation/pact` should be included as well to support running `skyux pact`.

**Comment by Blackbaud-BobbyEarl** [comment]
Released in [1.5.0](https://github.com/blackbaud/skyux-sdk-builder-plugin-migrate/blob/master/CHANGELOG.md#150-2019-04-02)
