### ISSUE TITLE
Migrate plugin adds import but module doesn't include component

### ISSUE THREAD

**Issue by Blackbaud-TomRamsey** [blackbaud/skyux-sdk-builder-plugin-migrate#39]
The migrate plugin added:

import {
  ListFilterModel,
  SkyListComponent
} from '@skyux/list-builder';

However, ListFilterModel doesn't exist on the module of @skyux/list-builder.  IntelliSense suggests @skyux/list-builder/modules/list/state

**Comment by Blackbaud-SteveBrush** [comment]
Duplicate: https://github.com/blackbaud/skyux-list-builder/issues/30
