### ISSUE TITLE
Migrate plugin doesn't update SkyModalService

### ISSUE THREAD

**Issue by Blackbaud-TomRamsey** [blackbaud/skyux-sdk-builder-plugin-migrate#40]
Migrate plugin runs, and ignores `import { SkyModalService } from '@blackbaud/skyux/dist/modules/modal/modal.service';` when it needs to remap it to part of the @skyux/modals import

**Comment by Blackbaud-PaulCrowder** [comment]
It's being ignored because the type is being imported directly from the module's file rather than the `@blackbaud/skyux/dist/core` barrel.  I'll look at making the match for the import path more liberal so it can catch these types of imports.
