### ISSUE TITLE
skyux errors out during migration - no package found for SkyRowComponent

### ISSUE THREAD

**Issue by GiorgioG** [blackbaud/skyux-sdk-builder-plugin-migrate#49]
Updating SKY UX imports in src\app\student-payment-plan\summary\student-payment-plan-summary.component.spec.ts...
(node:19988) UnhandledPromiseRejectionWarning: Error: No package found for SkyRowComponent!
    at createImportList (C:\Users\giorgio.galante\AppData\Roaming\npm\node_modules\@skyux-sdk\builder-plugin-migrate\lib\import-paths.js:50:13)
    at Object.fixImportPaths (C:\Users\giorgio.galante\AppData\Roaming\npm\node_modules\@skyux-sdk\builder-plugin-migrate\lib\import-paths.js:162:25)
(node:19988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Blackbaud-SteveBrush** [comment]
Curious why you need this type exported?

**Comment by GiorgioG** [comment]
@Blackbaud-SteveBrush I'm not sure, it looks like it's being used exclusively in our unit tests.

**Comment by Blackbaud-SteveBrush** [comment]
I gotcha. I'm assuming your unit test is verifying the row component exists? Instead of referencing the component type, perhaps you could search against the CSS class name instead (`.sky-row`)?

I'm going to close this for now, since it's not the intent to export this type.
