### ISSUE TITLE
Use preferred method for injecting global style sheets

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-builder-plugin-migrate#5]
Currently, the following line is added to the `AppSkyModule`:

```
require('style-loader!@skyux/theme/css/sky.css');
```

However, we recently added a new feature to the skyuxconfig.json file that allows for global stylesheets to be added automatically:

```
{
  "app": {
    "styles": [
      "./node_modules/@skyux/theme/css/sky.css"
    ]
  }
}
```

**Comment by Blackbaud-PaulCrowder** [comment]
Awesome!  I'll definitely change that.
